# Generated by Django 3.2.8 on 2021-12-14 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_userprofile_banner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfolio',
            name='category',
        ),
        migrations.AddField(
            model_name='blog',
            name='category',
            field=models.ManyToManyField(related_name='blog', to='main.Category', verbose_name='Category'),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='link',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
